name: Keep alive cron job
on:
  schedule:
    - cron: "0 */4 * * *" #https://crontab.guru/every-4-hours
  workflow_dispatch:
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call endpoint to keep the database alive
        run: |
          curl --request PUT \
          --url '${{ secrets.KEEP_ALIVE_URL }}' \
          --header 'x-keep-alive-api-secret: ${{ secrets.KEEP_ALIVE_API_SECRET }}'
