name: Keep alive cron job
on:
  schedule:
    - cron: "0 12 * * *" # https://crontab.guru/#0_12_*_*_*
  workflow_dispatch:
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call endpoint to keep the database alive
        run: |
          curl --request PUT \
          --url '${{ secrets.KEEP_ALIVE_URL }}/api/keep-alive' \
          --header 'x-keep-alive-api-secret: ${{ secrets.KEEP_ALIVE_API_SECRET }}'
